kind: pipeline
type: docker
name: integration

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      pgconn:
        from_secret: PGCONN
    commands:
      - apt-get update && apt-get install -y nodejs npm
      - cd api/api && dotnet build

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      pgconn:
        from_secret: PGCONN
    commands:
      - cd api/test && dotnet test  