kind: pipeline
type: docker
name: integration

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - apt-get update && apt-get install -y nodejs npm
      - cd api && dotnet run
  
      
  - name: test
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - cd test && dotnet test     